### PR TITLE
Add LE_ADDITIONAL_OPTIONS option for certbot

### LINKED ISSUE #64: Make preferred chain configurable
Been using `umputun/nginx-le:latest` for a few years, and recently getting some scanner complaints about

```
|-Subject   : O=Digital Signature Trust Co./CN=DST Root CA X3
|-Not After : Sep 30 14:01:15 2021 GMT
```

This hasn't resolved over a few renewals. I presume this is related to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ somehow. IIUC for a long tail transition period there is still some kind of benefit in maintaining, or at least not disallowing, the "long chain" which ties to the X3 root. But in the long term the X1 / ISRG root would be preferrable.

I modified `le.sh` amending `--preferred-chain "ISRG Root X1"`, ran it, copied new key/cert/chain files in place, stop+started container. At least the complaint about 2021 expired CA went away, though this created some other issues; full chain was not included by default, R3 intermediary listed as "Extra download".

I am not entirely sure if shifting from the long chain to short chain / ISRG Root X1 would even entail some change in the way the key/cert/chain are copied, or if something that works for me could break things for others, hence not making a pull request.

But thought it might be worthile to open an Issue / feature request. Could there be something like a default variable with override capability

```
export LE_PREFERRED_CHAIN="ISRG Root X1"
...
certbot certonly ...  --preferred-chain "${LE_PREFERRED_CHAIN}" ...
```

?

Or if there's some way to do this already that I didn't think of, please advise and then let's close this Issue.

### PR DESCRIPTION
**Pull request by paskal**
Resolves #64.

### CODE REVIEW

**Comment by paskal** [comment]
@junousi that should cover your need.

**Comment by junousi** [comment]
Thanks! But unfortunately not:

```
/ # env|grep ^LE
LETSENCRYPT=true
LE_EMAIL=REDACTED
LE_ADDITIONAL_OPTIONS=--preferred-chain 'ISRG Root X1'
LE_FQDN=REDACTED
/ # sh le.sh
x509: Option -in needs a value
x509: Use -help for summary.
letsencrypt certificate will expire soon or missing, renewing...
['/usr/bin/certbot', 'certonly', '-t', '-n', '--agree-tos', '--renew-by-default', '--email', 'REDACTED', '--webroot', '-w', '/usr/share/nginx/html', '-d', 'REDACTED', '--preferred-chain', "'ISRG", 'Root', "X1'"]
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: Root X1'
failed to run certbot
```

This is exactly why I've been hesitant to make a PR since my `sh`-fu isn't quite up to par to make it work without `eval` or similar tricks.

I *think* I've tried most of the permutations of `\ ` escaping whitespace, `'\''` quoted singlequote, `\"` escaped double quote, singlequotes inside doubles with reasonable escaping, and vice versa. Life would be simpler if they'd made this parameter `ISRG_Root_X1` instead of whitespace delimited :)

Thanks again for the PR, unfortunately I don't have the resources to perfect the implementation itself but can definitely do some testing.

**Comment by paskal** [comment]
I've tested it now, should work with quotes around everything like `'--debug --preferred-chain "ISRG Root X1"'` and without like `--preferred-chain "ISRG Root X1" --debug`.

**Comment by junousi** [comment]
Can confirm, works for my usecase now.

**Pull request merged**
