### PR TITLE
Add support for running docker-entrypoint.d scripts

### LINKED ISSUE #74: Support using environment variables in nginx config
In the official nginx image there is an option to define nginx configurations as templates where you can use environment variables which would be substituted on the container start.

I don't think there is something like that in your image.

Basically I need to replace DOMAIN1 and DOMAIN2 with environment variable values in the following snippet:

```nginx
map $host $backend {
    ${DOMAIN1} service1:1234;
    ${DOMAIN2} service2:1234;
}
```

Are there any workarounds that you can suggest? Or I can work on implementing that feature

### PR DESCRIPTION
**Pull request by krevedkokun**
Should fix #74

### CODE REVIEW

**Comment by paskal** [comment]
Could you please document it in Readme and maybe add an example script and commented out mounting of that script into docker-compose.yaml? Otherwise the feature would be there but no one would know about it.

**Comment by krevedkokun** [comment]
@paskal done

**Review by paskal — APPROVED** [review]
LGTM. If I got it correctly the `envsubst` is a benefit of inheriting the official nginx image.
Just one question, did you test the example docker-compose?

**Comment by krevedkokun** [comment]
@paskal that's correct, envusbst substitution is part of official nginx image. 
Yes, I've tested docker-compose and it works as expected

**Comment by KGOH** [comment]
@paskal sup. Just wondering when this PR will be merged? I need this feature too

**Pull request merged**
